apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-api
  labels:
    app: music-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-api
  template:
    metadata:
      labels:
        app: music-api
    spec:
      containers:
        - name: music-api
          image: diashabarmina/music-recommendation-api:2984915
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-service:5000"
            - name: MODEL_NAME
              value: "music-als-recommender"
            - name: MODEL_STAGE
              value: "Production"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 5
