apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-pvc
  namespace: music-rec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: music-rec
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: music-rec
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z postgres-service 5432; do
                echo "Waiting for postgres..."
                sleep 2
              done

        - name: pull-artifacts
          image: python:3.12-slim
          command:
            - sh
            - -c
            - |
              apt-get update -qq && apt-get install -y git --no-install-recommends

              pip install dvc --quiet

              git clone https://github.com/DianaBarmina/music-recommendation-mlops.git /tmp/repo
              cd /tmp/repo

              dvc remote modify dagshub auth basic
              dvc remote modify dagshub user $DAGSHUB_USERNAME
              dvc remote modify dagshub password $DAGSHUB_TOKEN


              dvc pull models/als_model.pkl
              dvc pull data/processed/users_map.parquet
              dvc pull data/processed/items_map.parquet
              dvc pull data/processed/train_matrix.npz
              dvc pull data/processed/reference/reference_dataset.parquet

              dvc pull data/raw/march
              dvc pull data/raw/january
              dvc pull data/raw/february

              cp models/als_model.pkl /app/models/als_model.pkl
              mkdir -p /app/data/processed/reference
              cp data/processed/users_map.parquet /app/data/processed/users_map.parquet
              cp data/processed/items_map.parquet /app/data/processed/items_map.parquet
              cp data/processed/train_matrix.npz /app/data/processed/train_matrix.npz
              cp data/processed/reference/reference_dataset.parquet \
                   /app/data/processed/reference/reference_dataset.parquet

              mkdir -p /app/data/raw
              cp -r data/raw/march /app/data/raw/march
              cp -r data/raw/january /app/data/raw/january
              cp -r data/raw/february /app/data/raw/february

              echo "All artifacts pulled successfully"
          env:
            - name: DAGSHUB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dvc-credentials
                  key: DAGSHUB_USERNAME
            - name: DAGSHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dvc-credentials
                  key: DAGSHUB_TOKEN
          volumeMounts:
            - name: model-data
              mountPath: /app/models
            - name: app-data
              mountPath: /app/data

      containers:
        - name: api
          image: diashabarmina/music-recommendation-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: mlops-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mlops-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mlops-secrets
                  key: SECRET_KEY
          volumeMounts:
            - name: model-data
              mountPath: /app/models
            - name: app-data
              mountPath: /app/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: model-data
          persistentVolumeClaim:
            claimName: model-pvc
        - name: app-data
          persistentVolumeClaim:
            claimName: data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: music-rec
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
