apiVersion: v1
kind: Secret
metadata:
  name: mlops-secrets
  namespace: music-rec
type: Opaque
stringData:
  DATABASE_URL: "postgresql://mlops:mlops_password@postgres-service:5432/mlops_db"
  SECRET_KEY: "supersecretkey_change_in_production"
